# Generated by Django 5.2.4 on 2025-07-26 09:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdMast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(help_text='Unique product code', max_length=50, unique=True)),
                ('product_name', models.CharField(help_text='Product name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('unit', models.CharField(help_text='Unit of measurement (kg, pcs, etc.)', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_stock', models.PositiveIntegerField(default=0, help_text='Minimum stock level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Master',
                'verbose_name_plural': 'Product Masters',
                'db_table': 'prodmast',
            },
        ),
        migrations.CreateModel(
            name='StckMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique transaction ID', max_length=50, unique=True)),
                ('transaction_date', models.DateTimeField(help_text='Transaction date and time')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Adjustment')], help_text='Type of transaction', max_length=3)),
                ('reference_number', models.CharField(blank=True, help_text='Reference number (PO, Invoice, etc.)', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('created_by', models.CharField(help_text='User who created the transaction', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'db_table': 'stckmain',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='StckDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity moved', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of transaction', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('batch_number', models.CharField(blank=True, help_text='Batch/Lot number', max_length=50)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date if applicable', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Item-specific remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product involved in transaction', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.prodmast')),
                ('stck_main', models.ForeignKey(help_text='Reference to main transaction', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.stckmain')),
            ],
            options={
                'verbose_name': 'Stock Detail',
                'verbose_name_plural': 'Stock Details',
                'db_table': 'stckdetail',
                'unique_together': {('stck_main', 'product')},
            },
        ),
    ]
